#pragma once
// エンジンが提供する主なヘッダをひとまとめにインクルードするアグリゲータ
#include <engine/basic_component.hpp>
#include <engine/basic_system.hpp>
#include <engine/core.hpp>
#include <engine/core/forward_declarations.hpp>
#include <engine/graphics.hpp>
#include <engine/math.hpp>
#include <engine/utils.hpp>